export * from './MainPage/MainPage'
export * from './DetailsPage/DetailsPage'
export * from './ErrorsPage/E404Page'
export * from './MovieListPage/MovieListPage'
export * from './SearchPage/SearchPage'
export * from './SecurityPage/SecurityPage'
export * from './SupportPage/SupportPage'